<?php
$collection = $this->getRmaCollection();
$order = $this->getOrder();
?>
<div>
    <div class="page-title">
        <h1><?php echo $this->__("Returns for order #%s", $order->getIncrementId()) ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <button onclick="window.location.href='<?php echo Mage::getUrl('rma/guest/create')?>';" class="button pull-right"><span><span><?php echo $this->__('Request New Return')?></span></span></button>
    <br><br>
    <?php if ($collection->count()):

// echo $collection->getSelect();die;
        ?>
        <?php echo $this->getChildHtml('rma.toolbar')?>
        <table class="data-table" id="rma-table">
            <thead>
            <tr class="first last">
                <th><?php echo $this->__("RMA") ?></th>
                <th><?php echo $this->__("Date") ?></th>
                <th><?php echo $this->__("Status") ?></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($collection as $rma): ?>
                <tr>
                    <td><?php echo $rma->getIncrementId() ?>
                        <?php if ($rma->getLastComment() && !$rma->getLastComment()->getIsRead()): ?><span class="unread"></span><?php endif;?>
                    </td>
                    <td><?php echo Mage::helper('core')->formatDate($rma->getCreatedAt(), 'medium') ?></td>
                    <td><?php echo $rma->getStatusName() ?></td>
                    <td><a href="<?php echo $rma->getGuestUrl()?>"><?php echo $this->__('View Return') ?></a></td>
                </tr>
            <?php endforeach?>
            </tbody>
        </table>
    <?php echo $this->getChildHtml('rma.toolbar')?>
        <script type="text/javascript">decorateTable('rma-table')</script>
    <?php else: ?>
        <p><?php echo $this->__("There are no Returns") ?></p>
    <?php endif ?>
</div>