<div class="page-title">
    <h1><?php echo $this->__('Request RMA')?></h1>
</div>
<p>
    To request a new RMA or check the status of current RMA, please, fill the form:
</p>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getStep1PostUrl()?>" method="POST" id="rma-form-validate" >
    <div class='fieldset'>
        <h2 class="legend" id="order-information"><?php echo $this->__("Order Information") ?></h2>
        <ul class="form-list">
            <li>
                <label for="order_increment_id" class="required"><em>*</em><?php echo $this->__("Order #") ?></label>
                <div class="input-box">
                    <input type='text' name="order_increment_id" id='order_increment_id' class="input-text required-entry" value="<?php echo $this->getOrderIncrementId()?>"/>
                </div>
            </li>
            <li>
                <label for="email" class="required"><em>*</em><?php echo $this->__("Email or Last Name") ?></label>
                <div class="input-box">
                    <input type='text' name="email" id='email' class="input-text required-entry" value="<?php echo $this->getEmail()?>"/>
                </div>
            </li>
        </ul>
        <button type="submit" title="<?php echo $this->__("Next") ?>" class="button"><span><span><?php echo $this->__("Next") ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('rma-form-validate', true);
    //]]>
</script>