<div class="page-title">
    <h1><?php echo $this->__('Add New Credit Card') ?></h1>
</div>
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<form method="post" action="<?php echo $this->getUrl('ebizcharge/index/addCardPost/'); ?>" id="form-validate">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Billing Information'); ?></h2>
        <input type="hidden" name="mage_cust_id" value="<?php echo $this->getCustomer()->getId(); ?>" />
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="firstname" class="required"><em>*</em><?php echo $this->__('First Name'); ?></label>
                    <div class="input-box">
                        <input type="text" name="billing[firstname]" id="firstname" class="input-text required-entry" />
                    </div>
                </div>
                <div class="field">
                    <label for="lastname" class="required"><em>*</em><?php echo $this->__('Last Name'); ?></label>
                    <div class="input-box">
                        <input type="text" name="billing[lastname]" class="input-text required-entry" id="lastname"/>
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo $this->__('Email'); ?></label>
                    <div class="input-box">
                        <input type="text" name="billing[email]" class="input-text required-entry validate-email" id="email" />
                    </div>
                </div>
                <div class="field">
                    <label for="phone"><?php echo $this->__('Phone'); ?></label>
                    <div class="input-box">
                        <input type="text" name="billing[phone]" class="input-text" id="phone" />
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="company"><?php echo $this->__('Company'); ?></label>
                    <div class="input-box">
                        <input type="text" name="billing[company]" class="input-text" id="company" />
                    </div>
                </div>
            </li>
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
            <li class="wide">
                <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                <div class="input-box">
                    <input type="text" name="billing[street[]]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                </div>
            </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" name="billing[street[]]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php endfor; ?>
            <li class="fields">
                <div class="field">
                    <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                    <div class="input-box">
                        <input type="text" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"  title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                    </div>
                </div>
                <div class="field">
                    <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                    <div class="input-box">
                        <select id="region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                            <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
    //<![CDATA[
    $('region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
    //]]>
                        </script>
                        <input type="text" id="region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                    <div class="input-box">
                        <input type="text" name="billing[postcode]" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                    </div>
                </div>
                <div class="field">
                    <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                    <div class="input-box">
                        <?php echo $this->getCountryHtmlSelect() ?>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Payment Information'); ?></h2>
        <ul class="form-list">
            <li>
                <label for="cc_holder" class="required"><em>*</em><?php echo $this->__('Card Holder'); ?></label>
                <div class="input-box">
                    <input type="text" name="payment[cc_holder]" class="input-text required-entry" id="cc_holder" />
                </div>
            </li>
            <li>
                <label for="cc_num" class="required"><em>*</em><?php echo $this->__('Credit Card Number'); ?></label>
                <div class="input-box">
                    <input type="text" name="payment[cc_number]" class="input-text required-entry" id="cc_num" />
                </div>
            </li>
            <li>
                <label for="cc_type" class="required"><em>*</em><?php echo $this->__('Card type'); ?></label>
                <div class="input-box">
                    <select name="payment[cc_type]" class="required-entry" id="cc_type">
                        <option value=""><?php echo $this->__('Please select...'); ?></option>
                        <?php $avail_types = Mage::getSingleton('payment/config')->getCcTypes() ?>
                        <?php $types = Mage::getStoreConfig('payment/ebizcharge/cctypes') ?>
                        <?php foreach ($avail_types as $code => $text) : ?>
                            <?php if (in_array($code, explode(',', $types))): ?>
                                <option value="<?php echo $text; ?>"><?php echo $text; ?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </select>
                </div>
            </li>
            <li>
                <div class="field">
                    <label for="cc_exp_month" class="required"><em>*</em><?php echo $this->__('Expiration Date'); ?></label>
                    <div class="input-box">
                        <div class="v-fix">
                            <select name="payment[cc_exp_month]" class="required-entry" id="cc_exp_month" style="width: 100px !important;">
                                <option value="01"><?php echo $this->__('January'); ?></option>
                                <option value="02"><?php echo $this->__('February'); ?></option>
                                <option value="03"><?php echo $this->__('March'); ?></option>
                                <option value="04"><?php echo $this->__('April'); ?></option>
                                <option value="05"><?php echo $this->__('May'); ?></option>
                                <option value="06"><?php echo $this->__('June'); ?></option>
                                <option value="07"><?php echo $this->__('July'); ?></option>
                                <option value="08"><?php echo $this->__('August'); ?></option>
                                <option value="09"><?php echo $this->__('September'); ?></option>
                                <option value="10"><?php echo $this->__('October'); ?></option>
                                <option value="11"><?php echo $this->__('November'); ?></option>
                                <option value="12"><?php echo $this->__('December'); ?></option>
                            </select>
                        </div>
                        <div class="v-fix">
                            <?php $years = range(date('Y', time()), date('Y', time()) + 10); ?>
                            <select name="payment[cc_exp_year]" style="width: 100px !important; margin-left: 5px;">
                                <?php foreach ($years as $year) : ?>
                                    <option value="<?php echo $year; ?>"><?php echo $year; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <label for="cc_cid"><?php echo $this->__('CVV'); ?></label>
                <div class="input-box">
                    <input type="text" name="payment[cc_cid]" class="input-text" id="cc_cid" style="width: 50px;" />
                </div>
            </li>
            <li>
                <label><input type="checkbox" name="payment[default]" value="1" /> <?php echo $this->__('Make this my default Payment Method'); ?></label>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->getUrl('ebizcharge/index/') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" class="button" title="<?php echo $this->__('Save Payment Method') ?>"><span><span><?php echo $this->__('Save Payment Method') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
//]]>
</script>
