<?php if ($this->isShowChart()): ?>
<div id="trendchart" style="width: 100%; height: 400px;"></div>
<script type="text/javascript">
    var chart;
    var recipeintTrendData = [];
    <?php foreach ($this->getCollection() as $row): ?>
        recipeintTrendData.push({
            total_rma_cnt: '<?php echo $row->getData('total_rma_cnt') ?>',
            date: '<?php echo $row->getData('created_at') ?>'
        });
    <?php endforeach ?>

    AmCharts.ready(function () {
        chart                    = new AmCharts.AmSerialChart();
        chart.pathToImages       = "/js/mirasvit/code/rma/lib/amcharts-3.4.5/images/";
        chart.dataProvider       = recipeintTrendData;
        chart.categoryField      = "date";

        var categoryAxis = chart.categoryAxis;
        categoryAxis.parseDates       = true;
        categoryAxis.minPeriod        = "DD";
        categoryAxis.dashLength       = 1;
        categoryAxis.minorGridEnabled = true;
        categoryAxis.position         = "top";
        categoryAxis.axisColor        = "#DADADA";

        var totalRmaCntAxis = new AmCharts.ValueAxis();
        totalRmaCntAxis.axisAlpha  = 1;
        totalRmaCntAxis.gridAlpha  = 0;
        totalRmaCntAxis.dashLength = 1;
        totalRmaCntAxis.title      = "Total RMAs Number";
        totalRmaCntAxis.inside     = true;
        totalRmaCntAxis.position   = "left";
        chart.addValueAxis(totalRmaCntAxis);

        var graph = new AmCharts.AmGraph();
        graph.id                = 'total_rma_cnt';
        graph.valueField        = "total_rma_cnt";
        graph.title             = "Total RMAs Number";
        graph.valueAxis         = totalRmaCntAxis;
        graph.balloonText       = "Total RMAs Number: [[value]]";
        graph.type              = "smoothedLine";
        graph.lineColor         = "#5fb503";
        graph.lineAlpha         = 1;
        graph.lineThickness     = 2;
        graph.bulletSize                  = 6;
        graph.bullet                      = 'round';
        graph.hideBulletsCount            = 50,
        graph.bulletBorderAlpha           = 1;
        graph.bulletColor                 = '#FFFFFF';
        graph.useLineColorForBulletBorder = true;
        graph.fillAlphas        = 0.1;
        chart.addGraph(graph);


        var legend = new AmCharts.AmLegend();
        legend.equalWidths = false;
        chart.addLegend(legend);

        var chartCursor            = new AmCharts.ChartCursor();
        chartCursor.cursorPosition = "mouse";
        chartCursor.pan            = true;
        chart.addChartCursor(chartCursor);

        var chartScrollbar = new AmCharts.ChartScrollbar();
        chartScrollbar.autoGridCount   = true;
        chartScrollbar.graph           = 'total_rma_cnt';
        chartScrollbar.scrollbarHeight = 40;
        chart.addChartScrollbar(chartScrollbar);

        chart.write("trendchart");
    });
</script>
<?php endif;?>