<?php
/**
 * eBizCharge Magento Plugin.
 * v1.0.4 - March 6th, 2013
 *
 * For assistance please contact support@ebizcharge.com
 *
 * Copyright (c) 2013 Century Business Solutions
 * All rights reserved.
 *
 *
 * @category    Mage
 * @package     Mage_Ebizcharge_Block_Form
 * @copyright   Copyright (c) 2013 Century Business Solutions  (www.centurybizsolutions.com)
 */
/**
 * Data Helper
 *
 * @category   Mage
 * @package    Mage_Ebizcharge
 * @name       Mage_Ebizcharge_Helper_Data
 * @author     Century Business Solutions <support@centurybizsolutions.com>
 */
?>
<fieldset class="form-list">
    <?php $_code = $this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <?php if ($this->hasToken()): ?>
            <li>
                <input type="hidden" name="payment[ebzc_cust_id]" value="<?php echo $this->getEbzcCustId(); ?>" id="ebzc_cust_id" />
                <label>
                    <input type="radio" name="payment[ebzc_option]" value="saved" class="validate-one-required-by-name" />
                    <?php echo $this->__('Select saved payment method'); ?>
                </label>
                <div class="input-box">
                    <ul>
                        <li>
                            <div class="input-box">
                                <select name="payment[ebzc_method_id]" id="<?php echo $_code; ?>_ebzc_method"
                                        class="required-entry validate-select">
                                    <option value="">Please select...</option>
                                    <?php $methods = $this->getPaymentMethods(); ?>
                                    <?php foreach ($methods as $method): ?>
                                        <option value="<?php echo $method->MethodID; ?>"
                                                <?php echo $method->SecondarySort ? "" : 'selected="selected"'; ?>><?php echo $method->MethodName . ' - Expires on: ' . $method->CardExpiration; ?></option>
                                            <?php endforeach; ?>
                                </select>
                            </div>
                        </li>
                        <?php /*
                          <li>
                          <div class="input-box">
                          <label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?> <span class="required">*</span></label><br />
                          <select id="<?php echo $_code ?>_cc_type2" name="payment[cc_type]" class="required-entry mw-validate-cc-type-select">
                          <option value=""><?php echo $this->__('--Please Select--') ?></option>
                          <?php $_ccType = $this->getInfoData('cc_type') ?>
                          <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                          <option value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                          <?php endforeach ?>
                          </select>
                          </div>
                          </li>
                          <li>
                          <div class="input-box">
                          <label for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?> <span class="required">*</span></label><br />
                          <div class="v-fix">
                          <select id="<?php echo $_code ?>_expiration" style="width:140px;" name="payment[cc_exp_month]" class="required-entry">
                          <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                          <?php foreach ($this->getCcMonths() as $k => $v): ?>
                          <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                          <?php endforeach ?>
                          </select>
                          </div>
                          <div class="v-fix" style="padding-left:5px;">
                          <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                          <select id="<?php echo $_code ?>_expiration_yr" style="width:103px;" name="payment[cc_exp_year]" class="required-entry">
                          <?php foreach ($this->getCcYears() as $k => $v): ?>
                          <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                          <?php endforeach ?>
                          </select>
                          </div>
                          </div>
                          </li>
                         */ ?>
                        <?php /*
                          <li>
                          <div class="input-box">
                          <label for="<?php echo $_code ?>_cc_cid"><?php echo $this->__('Card Verification Number') ?> <span class="required">*</span></label><br />
                          <div class="v-fix"><input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="required-entry input-text validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" style="width:3em;" value="" /></div>
                          &nbsp;
                          <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                          </div>
                          </li>
                         */ ?>
                    </ul>
                </div>
            </li>
            <li>
                <label>
                    <input type="radio" name="payment[ebzc_option]" value="new" class="validate-one-required-by-name" />
                    <?php echo $this->__('Add new payment method'); ?>
                </label>
                <div class="input-box">
                    <ul>
                        <li>
                            <div class="input-box">
                                <label for="<?php echo $_code ?>_cc_owner"><?php echo $this->__('Name on Card') ?> <span class="required">*</span></label><br/>
                                <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="required-entry input-text" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>"/>
                            </div>
                        </li>
                        <li>
                            <div class="input-box">
                                <label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?> <span class="required">*</span></label><br />
                                <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry mw-validate-cc-type-select">
                                    <option value=""><?php echo $this->__('--Please Select--') ?></option>
                                    <?php $_ccType = $this->getInfoData('cc_type') ?>
                                    <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                                        <option value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </li>
                        <li>
                            <div class="input-box">
                                <label for="<?php echo $_code ?>_cc_number"><?php echo "Credit Card Number" ?> <span class="required">*</span></label><br/>
                                <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
                            </div>
                        </li>
                        <li>
                            <div class="input-box">
                                <label for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?> <span class="required">*</span></label><br />
                                <div class="v-fix">
                                    <select id="<?php echo $_code ?>_expiration" style="width:140px;" name="payment[cc_exp_month]" class="required-entry">
                                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                                        <?php foreach ($this->getCcMonths() as $k => $v): ?>
                                            <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                                <div class="v-fix" style="padding-left:5px;">
                                    <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                                    <select id="<?php echo $_code ?>_expiration_yr" style="width:103px;" name="payment[cc_exp_year]" class="required-entry">
                                        <?php foreach ($this->getCcYears() as $k => $v): ?>
                                            <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="input-box">
                                <label for="<?php echo $_code ?>_cc_cid"><?php echo $this->__('Card Verification Number') ?> <span class="required">*</span></label><br />
                                <div class="v-fix"><input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="required-entry input-text validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" style="width:3em;" value="" /></div>
                                &nbsp;
                                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                            </div>
                        </li>
                        <?php if (!Mage::getStoreConfig('payment/ebizcharge/save_payment')): ?>
                            <li>
                                <div class="input-box">
                                    <label for="<?php echo $_code; ?>_save_payment">
                                        <input type="checkbox" name="payment[ebzc_save_payment]" id="<?php echo $_code; ?>_save_payment" value="1" />
                                        <?php echo $this->__('Save My Credit Card Info'); ?>
                                    </label>
                                </div>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </li>
            <li>
                <label>
                    <input type="radio" name="payment[ebzc_option]" value="update" class="validate-one-required-by-name" />
                    <?php echo $this->__('Update existing payment method'); ?>
                </label>
                <div class="input-box">
                    <ul>
                        <li>
                            <div class="input-box">
                                <select name="payment[ebzc_method_id]" id="<?php echo $_code; ?>_ebzc_method_edit"
                                        class="required-entry validate-select">
                                    <option value="">Please select...</option>
                                    <?php $methods = $this->getPaymentMethods(); ?>
                                    <?php foreach ($methods as $method): ?>
                                        <option value="<?php echo $method->MethodID; ?>"
                                                <?php echo $method->SecondarySort ? "" : 'selected="selected"'; ?>><?php echo $method->MethodName . ' - Expires on: ' . $method->CardExpiration; ?></option>
                                            <?php endforeach; ?>
                                </select>
                                <button type="button" class="button" value="Delete" id="delete-payment" style="margin-top: 5px;">
                                    <span><span>Delete Payment Method</span></span>
                                </button>
                                <span class="please-wait" id="ebzc-please-wait">
                                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif'); ?>" alt="Please wait..." title="Please wait..." class="v-middle"> Please wait...
                                </span>
                            </div>
                        </li>
                        <li>
                            <div class="input-box">
                                <label for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?> <span class="required">*</span></label><br />
                                <div class="v-fix">
                                    <select id="<?php echo $_code ?>_expiration" style="width:140px;" name="payment[cc_exp_month]" class="required-entry">
                                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                                        <?php foreach ($this->getCcMonths() as $k => $v): ?>
                                            <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                                <div class="v-fix" style="padding-left:5px;">
                                    <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                                    <select id="<?php echo $_code ?>_expiration_yr" style="width:103px;" name="payment[cc_exp_year]" class="required-entry">
                                        <?php foreach ($this->getCcYears() as $k => $v): ?>
                                            <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="input-box">
                                <label for="<?php echo $_code; ?>_avs_street">
                                    <?php echo $this->__('AVS Street'); ?> <span class="required">*</span>
                                </label>
                                <input type="text" name="payment[ebzc_avs_street]" id="<?php echo $_code ?>_avs_street" class="input-text required-entry"/>
                            </div>
                        </li>
                        <li>
                            <div class="input-box">
                                <label for="<?php echo $_code; ?>_avs_zip">
                                    <?php echo $this->__('AVS Zip'); ?> <span class="required">*</span>
                                </label>
                                <input type="text" name="payment[ebzc_avs_zip]" id="<?php echo $_code; ?>_avs_zip" class="input-text required-entry validate-number"/>
                            </div>
                        </li>
                    </ul>
                </div>
            </li>
        <?php else: ?>
            <li>
                <div class="input-box">
                    <label for="<?php echo $_code ?>_cc_owner"><?php echo $this->__('Name on Card') ?> <span class="required">*</span></label><br/>
                    <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="required-entry input-text" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>"/>
                </div>
            </li>
            <li>
                <div class="input-box">
                    <label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?> <span class="required">*</span></label><br />
                    <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry mw-validate-cc-type-select">
                        <option value=""><?php echo $this->__('--Please Select--') ?></option>
                        <?php $_ccType = $this->getInfoData('cc_type') ?>
                        <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                            <option value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </li>
            <li>
                <div class="input-box">
                    <label for="<?php echo $_code ?>_cc_number"><?php echo "Credit Card Number" ?> <span class="required">*</span></label><br/>
                    <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
                </div>
            </li>
            <li>
                <div class="input-box">
                    <label for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?> <span class="required">*</span></label><br />
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_expiration" style="width:140px;" name="payment[cc_exp_month]" class="required-entry">
                            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                            <?php foreach ($this->getCcMonths() as $k => $v): ?>
                                <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <div class="v-fix" style="padding-left:5px;">
                        <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                        <select id="<?php echo $_code ?>_expiration_yr" style="width:103px;" name="payment[cc_exp_year]" class="required-entry">
                            <?php foreach ($this->getCcYears() as $k => $v): ?>
                                <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </li>
            <li>
                <div class="input-box">
                    <label for="<?php echo $_code ?>_cc_cid"><?php echo $this->__('Card Verification Number') ?> <span class="required">*</span></label><br />
                    <div class="v-fix"><input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="required-entry input-text validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" style="width:3em;" value="" /></div>
                    &nbsp;
                    <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                </div>
            </li>
            <?php if (!Mage::getStoreConfig('payment/ebizcharge/save_payment')): ?>
                <li>
                    <div class="input-box">
                        <label for="<?php echo $_code; ?>_save_payment">
                            <input type="checkbox" name="payment[ebzc_save_payment]" id="<?php echo $_code; ?>_save_payment" value="1" />
                            <?php echo $this->__('Save My Credit Card Info'); ?>
                        </label>
                    </div>
                </li>
            <?php endif; ?>
        <?php endif; ?>
    </ul>

    <script type="text/javascript">
<?php if ($this->hasToken()): ?>
            $('delete-payment').on('click', function(evt) {
                var mid = $('<?php echo $_code; ?>_ebzc_method_edit').getValue();
                var cid = $('ebzc_cust_id').getValue();
                if (mid === '' || mid === undefined) {
                    alert('Please select a payment method to delete');
                } else {
                    $('ebzc-please-wait').show();
                    $('delete-payment').hide();
                    new Ajax.Request('<?php echo $this->getUrl('ebizcharge/index/delete'); ?>', {
                        method: 'post',
                        parameters: {cid: cid, mid: mid},
                        onSuccess: function(transport) {
                            var response = transport.responseText;
                            $('<?php echo $_code; ?>_ebzc_method_edit').update(response);
                            $('<?php echo $_code; ?>_ebzc_method').update(response);
                            alert('Deleted successfully.');
                            $('ebzc-please-wait').hide();
                            $('delete-payment').show();
                        },
                        onFailure: function(transport) {
                            alert('failed ' + transport.responseText);
                            $('ebzc-please-wait').hide();
                            $('delete-payment').show();
                        }
                    });
                }
            });
<?php endif; ?>
    </script>
</fieldset>

<script type="text/javascript">
//    $$('[name="payment[ebzc_option]"]').each(function(el) {
//        el.observe('change', function(ev) {
//            if ($(this).checked) {
//                $(this).up(1).down('.input-box').show();
//            } else {
//                $(this).up(1).down('.input-box').hide();
//            }
//        });
//    });
    function setOptionVisibility() {
        $$('input[name="payment[ebzc_option]"]').each(function(elm) {
            if (elm.up('label') && elm.up('label').next('div')) {
                var sub = elm.up('label').next('div');
                if (elm.checked) {
                    sub.show();
                    if (sub) {
                        sub.style.display = (false) ? 'none' : '';
                        sub.select('input', 'select', 'textarea', 'button').each(function(field) {
                            field.disabled = false;
                        });
                    }
                } else {
                    sub.hide();
                    if (sub) {
                        sub.style.display = (true) ? 'none' : '';
                        sub.select('input', 'select', 'textarea', 'button').each(function(field) {
                            field.disabled = true;
                        });
                    }
                }
            }
        });
    }
<?php if ($this->hasToken()): ?>
        setOptionVisibility();
        document.on('click', 'input[name="payment[ebzc_option]"]', function(evt, elm) {
            setOptionVisibility();
        });
        $('ebzc-please-wait').hide();
<?php endif; ?>
</script>
