<?php
$rma = $this->getRma();
?>
 <table cellspacing="0" cellpadding="0" border="0" width="650">
        <thead>
            <tr>
                <th align="left" width="220" bgcolor="#EAEAEA" style="font-size:11px;padding:3px 9px;border-bottom:1px"><?php echo $this->__("Product Name") ?></th>
                <th align="left" width="220" bgcolor="#EAEAEA" style="font-size:11px;padding:3px 9px;border-bottom:1px"><?php echo $this->__("SKU") ?></th>
                <th align="left" width="220" bgcolor="#EAEAEA" style="font-size:11px;padding:3px 9px;border-bottom:1px"><?php echo $this->__("Qty") ?></th>
                <th align="left" width="220" bgcolor="#EAEAEA" style="font-size:11px;padding:3px 9px;border-bottom:1px"><?php echo $this->__("Reason") ?></th>
                <th align="left" width="220" bgcolor="#EAEAEA" style="font-size:11px;padding:3px 9px;border-bottom:1px"><?php echo $this->__("Condition") ?></th>
                <th align="left" width="220" bgcolor="#EAEAEA" style="font-size:11px;padding:3px 9px;border-bottom:1px"><?php echo $this->__("Resolution") ?></th>
            </tr>
        </thead>
        <tbody>
<?php
$color = '#CCCCCC';
if ($rma): //when we preview template, rma is not set
    foreach($rma->getItemCollection() as $item):
        if (!$color) {
            $color = '#CCCCCC';
        } else {
            $color = '';
        }
    ?>
			<tr>
                <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>"><?php echo Mage::helper('rma')->getOrderItemLabel($item) ?></td>
                <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>"><?php echo $item->getProduct()->getSku() ?></td>
                <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>"><?php echo $item->getQtyRequested() ?></td>
                <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>"><?php echo $item->getReasonName() ?></td>
                <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>"><?php echo $item->getConditionName() ?></td>
                <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>"><?php echo $item->getResolutionName() ?></td>
			</tr>
<?php
endforeach;
endif;

?>
		</tbody>
</table>